name: "Release follow-up"
on:
  release:
    types: [published]

env:
  GO_VERSION: "1.15.x"

jobs:
  publish-homebrew-formula:
    name: Publish homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore bootstrap cache
        id: cache
        uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go/pkg/mod
            ${{ github.workspace }}/.tmp
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-

      - name: Bootstrap project dependencies
        if: steps.bootstrap-cache.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: Generate homebrew formula
        run: make homebrew-formula-generate

      - name: Set git configuration
        run: |
          git config user.name syft-release-pipeline
          git config user.email syft-release-pipeline@anchore.com

      - name: Publish updated homebrew formula
        run: make homebrew-formula-publish
        env:
          GITHUB_TOKEN: ${{ secrets.ANCHORE_GIT_READ_TOKEN }}

  update_version_check_file:
    name: Update version file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update version check file
        run: make version-check-update
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TOOLBOX_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TOOLBOX_AWS_SECRET_ACCESS_KEY }}

  build_and_push_container_image:
    name: Build, test, and publish container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TOOLBOX_DOCKER_USER }}
          password: ${{ secrets.TOOLBOX_DOCKER_PASS }}

      - name: Stage released artifacts
        run: make stage-released-linux-artifact

      - name: Build and tag Docker images
        run: make container-image-build

      - name: Smoke test Docker image
        run: make container-image-smoke-test

      - name: Push Docker images
        run: make container-image-push

  notify-on-failure:
    name: Notify on failure
    needs: [build_and_push_container_image, update_version_check_file, publish-homebrew-formula]
    runs-on: ubuntu-latest
    if: always()
    steps:
      # obtain the workflow conclusion via env (env.WORKFLOW_CONCLUSION)
      # values: neutral, success, skipped, cancelled, timed_out, action_required, failure
      - uses: technote-space/workflow-conclusion-action@v2

      - uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,workflow,job,commit,message,author
          text: The syft release-follow-up pipeline has failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TOOLBOX_WEBHOOK_URL }}
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure